### Site Settings ###
title               : amitojSingh
description         : >-                               # >- means to ignore newlines until "url:"
                      I turn coffee into code,
                      use tabs over spaces
                      and never broke production.

url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : "/portfolio"                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : amitojsingh/portfolYOU    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
#remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Amitoj Singh
  image             : me.jpg
  behance           : amitoj
# dribbble          : your_username
  email             : amitojsingh95@gmail.com
  facebook          : amitoj95
  github            : amitojsingh
# gitlab            : your_username
# instagram         : your_username
  linkedin          : singh-amitoj
  #medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : amitojsingh95
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

plugins:
  - jekyll-github-metadata

respository: amitojsingh/mentoraid

### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
